# Generated by Django 5.0.1 on 2024-02-24 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='Unknown', max_length=100000),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='nature_of_employement',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_Id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_salary',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
